[package]
name = "tectonic"
version = "0.1.0"
authors = ["Ricky Han <rickylqhan@gmail.com>"]

[lib]
name = "dtf"
path = "src/lib/dtf.rs"

[[bin]]
name = "tectonic-server"
path = "src/bin/server/main.rs"

[[bin]]
name = "tectonic-cli"
path = "src/bin/cli/main.rs"

[dependencies]
byteorder = "1.1.0"
postgres = "0.15"
config = "0.6"
clap = "~2.26"