[package]
name = "tectonicdb"
version = "0.1.7"
authors = ["Ricky Han <tectonic@rickyhan.com>"]
description = "fast datastore server for contiguous order book ticks"
repository = "https://github.com/rickyhan/tectonicdb"
keywords = ["finance", "datastore", "database", "financial"]
category = "Database"
license = "MIT"
readme = "README.md"
exclude = [
    "db/*",
]


[lib]
name = "dtf"
path = "src/lib/lib.rs"

[[bin]]
name = "tectonic-server"
path = "src/bin/server/main.rs"

[[bin]]
name = "tectonic-cli"
path = "src/bin/cli/main.rs"

# [[bin]]
# name = "gen_dtfs"
# publish = false
# path = "src/bin/gen_dtfs/main.rs"

[[bin]]
name = "gen_train_data"
publish = false
path = "src/bin/gen_train_data/main.rs"

[[bin]]
name = "dtfcat"
publish = true
path = "src/bin/dtfcat/main.rs"

[[bin]]
name = "dtfrebin"
publish = true
path = "src/bin/dtfrebin/main.rs"

[features]
default = []


[dependencies]
# These crates are strictly mandatory:
byteorder = "1.1.0"
bitflags = "1.0.0"
config = "0.6"
clap = "~2.26"
# Logging
fern = "0.4"
log = "0.3"
chrono = "0.4"

# postgres = "0.15"