[package]
name = "tectonicdb"
version = "0.1.6"
authors = ["Ricky Han <rickylqhan@gmail.com>"]
description = "fast datastore server for contiguous order book ticks"
repository = "https://github.com/rickyhan/tectonicdb"
keywords = ["finance", "datastore", "database", "financial"]
category = "Database"
license = "MIT"
readme = "README.md"
exclude = [
    "db/*",
]


[lib]
name = "dtf"
path = "src/lib/dtf.rs"

[[bin]]
name = "tectonic-server"
path = "src/bin/server/main.rs"

[[bin]]
name = "tectonic-cli"
path = "src/bin/cli/main.rs"

[[bin]]
name = "gen_dtfs"
publish = false
path = "src/bin/gen_dtfs/main.rs"

[[bin]]
name = "dtfcat"
publish = true
path = "src/bin/dtfcat/main.rs"

[[bin]]
name = "dtfrebin"
publish = true
path = "src/bin/dtfrebin/main.rs"

[dependencies]
byteorder = "1.1.0"
postgres = "0.15"
config = "0.6"
clap = "~2.26"
bitflags = "1.0.0"
log = "0.3"
fern = "0.4"
chrono = "0.4"
itertools = "0.7.2"
