[package]
name = "tectonic"
version = "0.1.0"
authors = ["Ricky Han <rickylqhan@gmail.com>"]
description = "fast datastore server for contiguous order book ticks"
repository = "https://github.com/rickyhan/tectonic"
keywords = ["finance", "datastore", "database", "financial"]
license = "MIT"
readme = "README.md"
exclude = [
    "db/*",
]


[lib]
name = "dtf"
path = "src/lib/dtf.rs"

[[bin]]
name = "tectonic-server"
path = "src/bin/server/main.rs"

[[bin]]
name = "tectonic-cli"
path = "src/bin/cli/main.rs"

[[bin]]
name = "gen_dtfs"
path = "src/bin/gen_dtfs/main.rs"

[dependencies]
byteorder = "1.1.0"
postgres = "0.15"
config = "0.6"
clap = "~2.26"