[package]
name = "tectonicdb"
version = "0.2.1"
authors = ["Ricky Han <tectonic@rickyhan.com>"]
description = "fast datastore server for contiguous order book ticks"
repository = "https://github.com/rickyhan/tectonicdb"
keywords = ["finance", "datastore", "database", "financial"]
category = "Database"
license = "MIT"
readme = "README.md"
exclude = [
    "db/*",
    "test/test-data/*",
]

[lib]
name = "libtectonic"
path = "src/lib/lib.rs"

[[bin]]
name = "tectonic-server"
path = "src/bin/server/main.rs"

[[bin]]
name = "tectonic-cli"
path = "src/bin/cli/main.rs"

[[bin]]
name = "dtfcat"
publish = true
path = "src/bin/dtfcat/main.rs"

[features]
default = ["gcs"]

gcs = [ "reqwest" ]




[dependencies]
# These crates are mandatory:
byteorder = "1.1.0"
bitflags = "1.0.0"
config = "0.6"
clap = "~2.26"
circular-queue = "0.2.0"

# Logging
fern = "0.4"
log = "0.3"
chrono = "0.4"
time = "0.1.38"

serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
uuid = "0.5.1"
tokio-core = "0.1"
tokio-io = "0.1"
futures = "0.1.14"

# google storage
reqwest = { version = "0.8.1", optional = true }
